before:
  hooks:
    - go mod tidy
builds:
  - id: parquet-cli
    main: ./cmd/parquet-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goarch: arm64
        goos: windows
    flags:
      - -v
    ldflags:
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .ShortCommit }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^example:'
